# Generated by Django 4.1.3 on 2022-11-23 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_books_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.author'),
        ),
        migrations.RemoveField(
            model_name='books',
            name='category',
        ),
        migrations.RemoveField(
            model_name='books',
            name='gener',
        ),
        migrations.AddField(
            model_name='books',
            name='category',
            field=models.ManyToManyField(to='books.categories'),
        ),
        migrations.AddField(
            model_name='books',
            name='gener',
            field=models.ManyToManyField(to='books.gener'),
        ),
    ]
